[package]
authors = ["Miitto <wpbickerton@gmail.com>"]
edition = "2024"
name = "save-manager"
version = "0.1.0"

[workspace]
members = ["api", "dx-ext"]
resolver = "3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.102"
dioxus = { version = "0.7.1", features = ["fullstack"] }
dx-ext = { path = "dx-ext" }
log = "0.4.32"
serde = "1.0.228"
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["io"] }
zip = { version = "8.6.0", default-features = false, features = [
  # "aes-crypto",
  # "bzip2",
  # "xz",
  "deflate",
  "deflate64",
  "lzma",
  "time",
  "zstd",
] }

[dependencies]
anyhow.workspace = true
api = { path = "api" }

chrono = "0.4.45"
dioxus = { workspace = true, features = ["router"] }
dioxus-cookie = "0.2.0"
dioxus-icons = { version = "0.1.0", default-features = false }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false, features = [
  "router",
] }
dioxus-sdk-time = "0.7.0"
directories = "6.0.0"
dx-ext.workspace = true
futures = "0.3.32"

log.workspace = true
serde.workspace = true
tokio = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
zip = { workspace = true, optional = true }

[features]
default = ["desktop"]
desktop = [
  "api/desktop",
  "dep:tokio",
  "dep:tokio-util",
  "dep:zip",
  "dioxus-cookie/desktop",
  "dioxus/desktop",
  "dx-ext/desktop",
]
server = [
  "api/server",
  "dioxus-cookie/server",
  "dioxus/server",
  "dx-ext/server",
]
web = ["api/web", "dioxus/web", "dx-ext/web"]

[dev-dependencies]
dioxus-ssr = "0.7.9"
